liip_imagine:
    driver: "gd"
    
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound